language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    # TINIFY_TOKEN=
    - secure: "iv09YFOZJ0xHjhITBVOwRTT4XIsQN+A0MkyIi4TIOEw6b3EuTAFGl2LHp40VyNhcSYcz/77OrrgeLLv3EggfWJ75Qvnk9HzbzS2Vt9/x2umLv4o8kCsaYUNIyEsacgd3dymkvZ4p8M06RU42wJ5AsNXb5yFEtKY5XqInAQ6mGKZYbn3RIOxhiOihH/beRsP1ihXnI8SaLxgEsG49bN4l4KOky4x7pjf80ZyVFiNvYsf6+35G7a3PWVWA72zjCFnaUiPuckHETIE2rPPWhEtXuSpt4wrl7OqGxT4ITa7fvdJU+g0OP32uY99Fk5IFfp6y/2JdEYeALzZsqFWQLGjHvcSh+smY8wu08uspt3bGcQhFfClobaGdLquDOL4NL2+HOhCFqC1SpqKLmNHxJ+Om4mO6jEBQdIFyOCyW0KQOaWF/Z70FaHcvcdtZcE5FPkHL8a9qgsLjd6LOZnzL4rft0SsVBNrJkJNVG5kwNnLdchB9HyYT11dbbgZ+mr81RUY92mnLdF8hkOyyQ6v8BRDiBsrrKns7nRXnsgR7IpUHIecTmuxAy+Q2Zqh8NLDJMNTcLzr077JZ4nvprd7TJ36m8hSelHb58t8vVjMG7zcsiFLQQEF0atCiste2dFdINYgUxmVqzft8IgNHtFxuD4p0g09inambNCTDitC7mnka78o="


before_install:
#  - echo "extension=php_curl.so" >> tests/php.ini
  - echo "TINIFY_TOKEN=${TINIFY_TOKEN}" >> tests/php.ini

matrix:
  allow_failures:
    - php: 7.0

script:
  - vendor/bin/tester -p php-cgi -c tests/php.ini tests

after_failure:
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
  - travis_retry composer update --no-interaction